# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gera valores de anova para RBCD teste
#'
#' @description Calcula valores utilizados para uma tabela de ANOVA de um delineamento em blocos completamente casualizados
#'
#' @param dados Data frame com colunas separadas para os tratamentos, os blocos e os resultados a serem analisados
#' @param x String com o nome da coluna dos tratamentos
#' @param y String com o nome da coluna dos resultados
#' @param bloco String com o nome da coluna dos blocos
#'
#' @return Objeto de tipo lista contendo todos os valores utilizados para o calculo da tabela da ANOVA, os valores da tabela da ANOVA e os parâmetros estimados.
#'
#' @examples
#'
#' bloco_incompleto(4, 4, 2)$dados %>%
#'   anova_bibd("Trat", "resultado", "bloco")
#'
#' @export
#'
anova_bibd <- function(dados, x, y, bloco) {
    .Call(`_planejamento_anova_bibd`, dados, x, y, bloco)
}

#' Gera valores de anova para Quadrados Latinos
#'
#' @description Calcula valores utilizados para uma tabela de ANOVA de um delineamento em quadrados latinos
#'
#' @param dados Data frame com colunas separadas para os tratamentos, os blocos e os resultados a serem analisados
#' @param x String com o nome da coluna dos tratamentos
#' @param chi String com o nome da coluna dos outros tratamentos
#' @param y String com o nome da coluna dos resultados
#' @param linha String com o nome da coluna do data frame que representa a linha do quadrado latino
#' @param coluna String com o nome da coluna do data frame que representa a coluna do quadrado latino
#'
#' @import glue
#' @import tidyr
#'
#' @return Objeto de tipo lista contendo todos os valores utilizados para o calculo da tabela da ANOVA, os valores da tabela da ANOVA e os parâmetros estimados.
#' 
#' @examples
#'
#' quadrados_latinos(4)$dados %>%
#'  anova_lsqd("tratamento", "resultado", "linha", "coluna")
#'
#' @export
#'
anova_glsqd <- function(dados, x, chi, y, linha, coluna) {
    .Call(`_planejamento_anova_glsqd`, dados, x, chi, y, linha, coluna)
}

#' Gera valores de anova para Quadrados Latinos
#'
#' @description Calcula valores utilizados para uma tabela de ANOVA de um delineamento em quadrados latinos
#'
#' @param dados Data frame com colunas separadas para os tratamentos, os blocos e os resultados a serem analisados
#' @param x String com o nome da coluna dos tratamentos
#' @param y String com o nome da coluna dos resultados
#' @param linha String com o nome da coluna do data frame que representa a linha do quadrado latino
#' @param coluna String com o nome da coluna do data frame que representa a coluna do quadrado latino
#' @param replica String com o nome da coluna do data frame que representa as replicas
#'
#' @import glue
#' @import tidyr
#'
#' @return Objeto de tipo lista contendo todos os valores utilizados para o calculo da tabela da ANOVA, os valores da tabela da ANOVA e os parâmetros estimados.
#' 
#' @examples
#'
#' quadrados_latinos(4)$dados %>%
#'  anova_lsqd("tratamento", "resultado", "linha", "coluna")
#'
#' @export
#'
anova_lsqd <- function(dados, x, y, linha, coluna, replica = "") {
    .Call(`_planejamento_anova_lsqd`, dados, x, y, linha, coluna, replica)
}

#' Gera valores de anova para RBCD teste
#'
#' @description Calcula valores utilizados para uma tabela de ANOVA de um delineamento em blocos completamente casualizados
#'
#' @param dados Data frame com colunas separadas para os tratamentos, os blocos e os resultados a serem analisados
#' @param x String com o nome da coluna dos tratamentos
#' @param y String com o nome da coluna dos resultados
#' @param bloco String com o nome da coluna dos blocos
#'
#' @return Objeto de tipo lista contendo todos os valores utilizados para o calculo da tabela da ANOVA, os valores da tabela da ANOVA e os parâmetros estimados.
#'
#' @examples
#'
#' anova_rbcd(mtcars, "gear", "hp", "carb")
#'
#' @export
#'
anova_rbcd <- function(dados, x, y, bloco) {
    .Call(`_planejamento_anova_rbcd`, dados, x, y, bloco)
}

#' Soma por grupos
#'
#' @description Faz a soma de um vetor por grupos, semelhante a `tapply(y, x, sum)`.
#'
#' @param x Vetor numérico dos valores que serão somados
#' @param grupo Vetor com fatores que agruparão os dados
#'
#' @return Vetor com as somas resumidas de cada grupo.
#'
soma_grupo <- function(x, grupo) {
    .Call(`_planejamento_soma_grupo`, x, grupo)
}

#' Multiplicação de matrizes
#'
#' @description Multplica duas matrizes.
#'
#' @param m Primeira matriz
#' @param v Segunda matriz
#'
#' @return Matriz.
#'
mmult <- function(m, v) {
    .Call(`_planejamento_mmult`, m, v)
}

#' Ordenar vetor
#'
#' @description Gera um vetor com os indices para ordenação.
#'
#' @param x Vetor
#'
#' @return Vetor numerico com indices ordenados de forma que os dados fiquem ordenados.
#'
Rcpp_sort <- function(x) {
    .Call(`_planejamento_Rcpp_sort`, x)
}

